### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by sambeano7** [favianrizqulloh/discord-clock#1]
This isn't an issue but is there a way to make it read military time instead of 12 hr time?

**Comment by favianrizqulloh** [comment]
The time format is already a military-based (or 24-hour clock)
![image](https://user-images.githubusercontent.com/48427319/80275527-04e9a600-870c-11ea-926b-f06466b12e4c.png)

Read more about formatting at https://momentjs.com/docs/#/displaying/format/
